server:
  port:
    9090


spring.datasource.url: jdbc:oracle:thin:@localhost:49161:xe
spring:
  datasource:
    username: system
    password: oracle
    driver-class: oracle.jdbc.driver.OracleDriver